<?php declare(strict_types=1);

namespace Souplette\Html\Parser\Tokenizer;

/**
 * @see https://html.spec.whatwg.org/multipage/parsing.html#parse-errors
 */
enum ParseErrors
{
    case ABRUPT_CLOSING_OF_EMPTY_COMMENT;
    case ABRUPT_DOCTYPE_PUBLIC_IDENTIFIER;
    case ABRUPT_DOCTYPE_SYSTEM_IDENTIFIER;
    case ABSENCE_OF_DIGITS_IN_NUMERIC_CHARACTER_REFERENCE;
    case CDATA_IN_HTML_CONTENT;
    case CHARACTER_REFERENCE_OUTSIDE_UNICODE_RANGE;
    case CONTROL_CHARACTER_IN_INPUT_STREAM;
    case CONTROL_CHARACTER_REFERENCE;
    case DUPLICATE_ATTRIBUTE;
    case END_TAG_WITH_ATTRIBUTES;
    case END_TAG_WITH_TRAILING_SOLIDUS;
    case EOF_BEFORE_TAG_NAME;
    case EOF_IN_CDATA;
    case EOF_IN_COMMENT;
    case EOF_IN_DOCTYPE;
    case EOF_IN_SCRIPT_HTML_COMMENT_LIKE_TEXT;
    case EOF_IN_TAG;
    case INCORRECTLY_CLOSED_COMMENT;
    case INCORRECTLY_OPENED_COMMENT;
    case INVALID_CHARACTER_SEQUENCE_AFTER_DOCTYPE_NAME;
    case INVALID_FIRST_CHARACTER_OF_TAG_NAME;
    case MISSING_ATTRIBUTE_VALUE;
    case MISSING_DOCTYPE_NAME;
    case MISSING_DOCTYPE_PUBLIC_IDENTIFIER;
    case MISSING_DOCTYPE_SYSTEM_IDENTIFIER;
    case MISSING_END_TAG_NAME;
    case MISSING_QUOTE_BEFORE_DOCTYPE_PUBLIC_IDENTIFIER;
    case MISSING_QUOTE_BEFORE_DOCTYPE_SYSTEM_IDENTIFIER;
    case MISSING_SEMICOLON_AFTER_CHARACTER_REFERENCE;
    case MISSING_WHITESPACE_AFTER_DOCTYPE_PUBLIC_KEYWORD;
    case MISSING_WHITESPACE_AFTER_DOCTYPE_SYSTEM_KEYWORD;
    case MISSING_WHITESPACE_BEFORE_DOCTYPE_NAME;
    case MISSING_WHITESPACE_BETWEEN_ATTRIBUTES;
    case MISSING_WHITESPACE_BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS;
    case NESTED_COMMENT;
    case NONCHARACTER_CHARACTER_REFERENCE;
    case NONCHARACTER_IN_INPUT_STREAM;
    case NON_VOID_HTML_ELEMENT_START_TAG_WITH_TRAILING_SOLIDUS;
    case NULL_CHARACTER_REFERENCE;
    case SURROGATE_CHARACTER_REFERENCE;
    case SURROGATE_IN_INPUT_STREAM;
    case UNEXPECTED_CHARACTER_AFTER_DOCTYPE_SYSTEM_IDENTIFIER;
    case UNEXPECTED_CHARACTER_IN_ATTRIBUTE_NAME;
    case UNEXPECTED_CHARACTER_IN_UNQUOTED_ATTRIBUTE_VALUE;
    case UNEXPECTED_EQUALS_SIGN_BEFORE_ATTRIBUTE_NAME;
    case UNEXPECTED_NULL_CHARACTER;
    case UNEXPECTED_QUESTION_MARK_INSTEAD_OF_TAG_NAME;
    case UNEXPECTED_SOLIDUS_IN_TAG;
    case UNKNOWN_NAMED_CHARACTER_REFERENCE;
}
