# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: PHP ${{ matrix.php-version }} + ${{ matrix.dependencies }}
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        php-version:
          - '8.1'
          - '8.2'
        dependencies:
          - highest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: composer:v2, phpunit
      - name: Install Composer dependencies (${{ matrix.dependencies }})
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist --prefer-stable
      - name: Run tests with coverage
        run: phpunit -c phpunit.xml --coverage-clover tmp/clover.xml
      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: tmp/clover.xml
